/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "isyfact-standards"
include(":isy-sonderzeichen")
include(":isy-ueberwachung")
include(":isy-polling")
include(":isy-util")
include(":isy-serviceapi-core")
include(":isyfact-standards-bom")
include(":isy-exception-core")
include(":isy-sicherheit")
include(":isy-konfiguration")
include(":isy-logging")
include(":isy-aufrufkontext")
include(":isyfact-products-bom")
include(":isy-datetime")
include(":isy-batchrahmen")
include(":isy-persistence")
include(":isy-task")
