/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    implementation(project(":isy-logging"))
    implementation(project(":isy-task"))
    implementation(project(":isy-exception-core"))
    implementation("org.springframework:spring-context:5.3.21")
    implementation("org.springframework.boot:spring-boot:2.7.1")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.7.1")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.7.1")
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("org.springframework.boot:spring-boot-test:2.7.1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
}

description = "IsyFact-Konfiguration"

java {
    withJavadocJar()
}
