/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    testImplementation("junit:junit:4.13.2")
}

description = "IsyFact-Fehlerbehandlung (Basisklassen)"

java {
    withJavadocJar()
}
