/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    implementation(project(":isy-datetime"))
    implementation(project(":isy-exception-core"))
    implementation(project(":isy-logging"))
    implementation("org.springframework:spring-beans:5.3.21")
    implementation("org.springframework:spring-context:5.3.21")
    implementation("org.springframework:spring-jdbc:5.3.21")
    implementation("org.springframework:spring-orm:5.3.21")
    implementation("org.springframework:spring-tx:5.3.21")
    implementation("org.springframework.boot:spring-boot:2.7.1")
    implementation("org.springframework.boot:spring-boot-actuator:2.7.1")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.7.1")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.7.1")
    implementation("org.springframework.data:spring-data-jpa:2.7.1")
    implementation("org.hibernate:hibernate-core:5.6.9.Final")
    implementation("javax.persistence:javax.persistence-api:2.2")
    implementation("com.oracle.database.jdbc:ucp:19.11.0.0")
    implementation("org.springframework.boot:spring-boot-test-autoconfigure:2.7.1")
    implementation("jakarta.validation:jakarta.validation-api:3.0.2")
    testImplementation("org.mockito:mockito-core:4.5.1")
    testImplementation("org.springframework:spring-test:5.3.21")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
    testImplementation("com.h2database:h2:2.1.210")
    testImplementation("org.dbunit:dbunit:2.7.2")
    testImplementation("com.github.springtestdbunit:spring-test-dbunit:1.3.0")
    testImplementation("org.hibernate.validator:hibernate-validator:6.2.3.Final")
}

description = "IsyFact Persistence"

java {
    withJavadocJar()
}
