/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    implementation(project(":isy-datetime"))
    implementation("de.bund.bva.isyfact:isy-exception-sst:1.10.0")
    implementation(project(":isy-logging"))
    implementation("de.bund.bva.isyfact:isy-serviceapi-sst:1.10.0")
    implementation(project(":isy-task"))
    implementation("org.springframework:spring-aop:5.3.21")
    implementation("org.springframework:spring-beans:5.3.21")
    implementation("org.springframework:spring-context:5.3.21")
    implementation("org.springframework:spring-core:5.3.21")
    implementation("org.springframework.boot:spring-boot:2.7.1")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.7.1")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.7.1")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.7.1")
    implementation("javax.validation:validation-api:2.0.1.Final")
    implementation("org.springframework.security:spring-security-config:5.7.2")
    implementation("org.springframework.security:spring-security-web:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
    testImplementation("org.springframework:spring-test:5.3.21")
    testImplementation("org.springframework.boot:spring-boot-test:2.7.1")
    testImplementation("org.mockito:mockito-core:4.5.1")
    testImplementation("org.springframework.boot:spring-boot-starter-web:2.7.1")
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("ch.qos.logback:logback-core:1.2.8")
    testImplementation("ch.qos.logback:logback-classic:1.2.8")
    testImplementation("org.slf4j:slf4j-api:1.7.36")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.4.0")
    testImplementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.61")
    testImplementation("org.hibernate.validator:hibernate-validator:6.2.3.Final")
    compileOnly("javax.servlet:javax.servlet-api:3.1.0")
}

description = "IsyFact-Überwachung"

java {
    withJavadocJar()
}
