/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    implementation(project(":isy-aufrufkontext"))
    implementation(project(":isy-exception-core"))
    implementation(project(":isy-logging"))
    implementation(project(":isy-sicherheit"))
    implementation("org.springframework:spring-aop:5.3.21")
    implementation("org.springframework:spring-beans:5.3.21")
    implementation("org.springframework:spring-context:5.3.21")
    implementation("org.springframework:spring-core:5.3.21")
    implementation("org.springframework:spring-jdbc:5.3.21")
    implementation("org.springframework:spring-orm:5.3.21")
    implementation("org.springframework:spring-tx:5.3.21")
    implementation("org.springframework.boot:spring-boot:2.7.1")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.7.1")
    implementation("org.hibernate:hibernate-core:5.6.9.Final")
    implementation("ch.qos.logback:logback-classic:1.2.8")
    implementation("ch.qos.logback:logback-core:1.2.8")
    implementation("commons-cli:commons-cli:1.5.0")
    implementation("org.slf4j:slf4j-api:1.7.36")
    testImplementation("org.mockito:mockito-core:4.5.1")
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("org.springframework:spring-test:5.3.21")
    testImplementation("org.springframework.boot:spring-boot-test:2.7.1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
    testImplementation("com.h2database:h2:2.1.210")
    testImplementation(project(":isy-serviceapi-core"))
}

description = "IsyFact-Batchrahmen"

java {
    withJavadocJar()
}
