/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    implementation(project(":isy-logging"))
    implementation(project(":isy-exception-core"))
    implementation("de.bund.bva.isyfact:isy-exception-sst:1.10.0")
    implementation("de.bund.bva.isyfact:isy-serviceapi-sst:1.10.0")
    implementation(project(":isy-sicherheit"))
    implementation(project(":isy-aufrufkontext"))
    implementation("ma.glasnost.orika:orika-core:1.5.4")
    implementation("org.springframework:spring-aop:5.3.21")
    implementation("org.springframework:spring-beans:5.3.21")
    implementation("org.springframework:spring-context:5.3.21")
    implementation("org.springframework:spring-core:5.3.21")
    implementation("org.springframework:spring-tx:5.3.21")
    implementation("org.springframework:spring-web:5.3.21")
    implementation("org.springframework.boot:spring-boot:2.7.1")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.7.1")
    testImplementation("org.mockito:mockito-core:4.5.1")
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("org.springframework:spring-test:5.3.21")
    testImplementation("org.springframework.boot:spring-boot-test:2.7.1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
    testImplementation("org.springframework:spring-webmvc:5.3.21")
    testImplementation("org.apache.tomcat.embed:tomcat-embed-core:9.0.64")
    testImplementation("org.slf4j:slf4j-api:1.7.36")
    testImplementation("ch.qos.logback:logback-core:1.2.8")
    testImplementation("ch.qos.logback:logback-classic:1.2.8")
    compileOnly("javax.servlet:javax.servlet-api:3.1.0")
}

description = "IsyFact Service-API Anwendung"

java {
    withJavadocJar()
}
