/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.bund.bva.isyfact.java-conventions")
}

dependencies {
    implementation(project(":isy-exception-core"))
    implementation(project(":isy-logging"))
    implementation("org.springframework:spring-beans:5.3.21")
    implementation("org.springframework:spring-web:5.3.21")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.7.3")
    testImplementation("org.mockito:mockito-core:4.5.1")
    testImplementation("org.springframework:spring-test:5.3.21")
    testImplementation("org.springframework.boot:spring-boot-test:2.7.1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("org.apache.tomcat.embed:tomcat-embed-core:9.0.64")
    testImplementation("org.slf4j:jul-to-slf4j:1.7.36")
    testImplementation("org.hibernate.validator:hibernate-validator:6.2.3.Final")
    compileOnly("javax.servlet:javax.servlet-api:3.1.0")
}

description = "IsyFact-Aufrufkontext"

java {
    withJavadocJar()
}
